alias ll='ls -lh'
alias lla='ls -alh'
alias llrt='ls -rtlh'
alias bb='cd ../..'
alias b='cd ..'
alias rm='rm -i'
alias cp='cp -i'
alias cpf='cp -f'
alias mv='mv -i'
alias duu='du -h --max-depth 1'
alias df='df -h'
alias h='history | grep '
alias pss='ps awx | grep '
alias gs='git status --untracked-files=no'
alias sar='sudo service apache2 restart'
alias srl='sudo service apache2 reload'
